document.writeln("<div class=\'footer\' style=\'overflow-x: hidden;\'>");
document.writeln("			<div class=\'row\' style=\'display: flex; justify-content: center;\'>");
document.writeln("				<div class=\'col-md-3\'>");
document.writeln("					<div class=\'text-container about\'>");
document.writeln("						<h4>联系我们</h4>");
document.writeln("						<p class=\'white\'><img src=\'images/icon/phone.png\'> : 021-58055790</p>");
document.writeln("						<p class=\'white\'><img src=\'images/icon/iphone.png\' class=\'small\'> : +86-18721633726 、+86-18017032987</p>");
document.writeln("						<p class=\'white\'><img src=\'images/icon/email.png\' class=\'small\'> : qun_wang@linxvalley.com </p>");
document.writeln("						<p class=\'white\'><img src=\'images/icon/email.png\' class=\'small\'> : yanqian_liao@linxvalley.com </p>");
document.writeln("						<p class=\'white\'><img src=\'images/icon/adress.png\' class=\'small\'> : 上海市浦东新区灵岩南路295号12号楼12-103室</p>");
document.writeln("					</div>");
document.writeln("			");
document.writeln("				</div>");
document.writeln("			");
document.writeln("				<div class=\'col-md-3\'>");
document.writeln("					<div class=\'text-container\'>");
document.writeln("						<h4>我们的使命</h4>");
document.writeln("						<p class=\'white\'>持续研发最落地的制造管理信息系统</p>");
document.writeln("						<p class=\'white\'>通过数字化服务提升制造企业效率</p>");
document.writeln("						<p class=\'white\'>提升质量水平，降低浪费和库存</p>");
document.writeln("						<p class=\'white\'>我们依靠企业生存，企业依靠我们发展</p>");
document.writeln("						<p class=\'white\'>凝聚我们的力量，收获明日的辉煌</p>");
document.writeln("					</div>");
document.writeln("				</div>");
document.writeln("				<div class=\'col-md-2\'>");
document.writeln("					<div class=\'text-container\' style=\'text-align: center;margin: 0 auto;\'>");
document.writeln("						<h6 style=\'color: #FFFFFF\'>社会荣誉</h6>");
document.writeln("						<img src=\'images/rongyu1.png\' alt=\'\' style=\'width: 100%;\'>");
document.writeln("					</div>");
document.writeln("				</div>");
document.writeln("				 ");
document.writeln("				<div class=\'col-md-2\'>");
document.writeln("					<div class=\'text-container\' style=\'text-align: center;margin: 0 auto;\'>");
document.writeln("						<h6 style=\'color: #FFFFFF\'>企业证书</h6>");
document.writeln("						<img src=\'images/rongyu2.png\' alt=\'\' style=\'width: 100%;\'>");
document.writeln("					</div>");
document.writeln("				</div>");
document.writeln("				 ");
document.writeln("			</div>");
document.writeln("		</div>");
document.writeln("		<div class=\'copyright\'>");
document.writeln("			<div class=\'container\'>");
document.writeln("				<div class=\'row\'>");
document.writeln("					<div class=\'col-lg-12\'>");
document.writeln("						<p class=\'p-small\'>备案号：沪ICP备16031549号-1　 <a>沪公网安备 31010602003203号</a></p>");
document.writeln("					</div>");
document.writeln("				</div>");
document.writeln("			</div>");
document.writeln("		</div>");